# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.startup.homepage", "http://active.dcarf/work/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.11");
user_pref("dom.disable_open_during_load", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_submit_insecure.show_once", false);
user_pref("mozex.command.aim", "");
user_pref("mozex.command.download", "");
user_pref("mozex.command.ed2k", "");
user_pref("mozex.command.ftp", "/bin/killall pjsua; /bin/killall firefox-bin");
user_pref("mozex.command.irc", "/bin/screen -d -m /bin/pjsua --id sip:%u@%h --registrar sip:%h --username %u --password %p --realm asterisk --auto-answer 200 --no-vad --quality 10");
user_pref("mozex.command.mailer", "");
user_pref("mozex.command.news", "/bin/killall pjsua");
user_pref("mozex.command.source", "");
user_pref("mozex.command.source.hotkey", "");
user_pref("mozex.command.ssh", "");
user_pref("mozex.command.telnet", "");
user_pref("mozex.command.textarea", "");
user_pref("mozex.command.textarea.file.extension", "");
user_pref("mozex.command.textarea.hotkey", "");
user_pref("mozex.command.textarea.unwrap", false);
user_pref("mozex.command.textarea.utf", false);
user_pref("mozex.debug.exec", false);
user_pref("mozex.general.tmpdir", "");
user_pref("mozex.intercept.ftp", true);
user_pref("mozex.intercept.irc", true);
user_pref("mozex.intercept.mailto", false);
user_pref("mozex.intercept.news", true);
user_pref("mozex.intercept.ssh", false);
user_pref("mozex.intercept.telnet", false);
user_pref("mozex.universal.command", "");
user_pref("mozex.universal.schemes", "");

